### ISSUE TITLE
Unicode Character causes harvest error

### ISSUE THREAD

**Issue by lukecampbell** [ioos/catalog#201]
```
ioos_catalog.tasks.harvest.harvest(ObjectId('526039ef8c0db35c6a0854a8')) from default
Traceback (most recent call last):
  File "/home/monitoring/.virtualenvs/monitoring/lib/python2.7/site-packages/rq/worker.py", line 407, in perform_job
    rv = job.perform()
  File "/home/monitoring/.virtualenvs/monitoring/lib/python2.7/site-packages/rq/job.py", line 386, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/home/monitoring/ioos-service-monitor/ioos_catalog/tasks/debug.py", line 10, in wrapper
    return func(*args, **kwargs)
  File "/home/monitoring/ioos-service-monitor/ioos_catalog/tasks/harvest.py", line 72, in harvest
    return DapHarvest(service).harvest()
  File "/home/monitoring/ioos-service-monitor/ioos_catalog/tasks/harvest.py", line 762, in harvest
    'metadata_value': unicode(dataset2ncml(cd.nc, url=self.service.get('url'))),
  File "/home/monitoring/.virtualenvs/monitoring/lib/python2.7/site-packages/petulantbear/netcdf2ncml.py", line 255, in dataset2ncml
    dataset2ncml_buffer(dataset,output,url)
  File "/home/monitoring/.virtualenvs/monitoring/lib/python2.7/site-packages/petulantbear/netcdf2ncml.py", line 238, in dataset2ncml_buffer
    parse_att(output,(attname,dataset.getncattr(attname)), indent)
  File "/home/monitoring/.virtualenvs/monitoring/lib/python2.7/site-packages/petulantbear/netcdf2ncml.py", line 124, in parse_att
    attvalue=sanatize(att[1])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 40: ordinal not in range(128)
```

We probably need to update petulantbear so that it can handle unicode properly.

**Comment by carmelortiz** [comment]
@lukecampbell The related issue is closed/fixed, can this one also be closed?
