### ISSUE TITLE
NDBC and CO-OPS sensorml2iso metadata update

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog#43]
Looks like the process to update the CO-OPS and NDBC SOS metadata via sensorml2iso hasn't run since 3/25.   

Here's a couple examples: 

CO-OPS:
https://data.ioos.us/dataset/urn-ioos-station-noaa-nos-co-ops-8729840-station-pensacola-fl1

NDBC:
https://data.ioos.us/dataset/mississippi-state-university-wave-glider-msg142

@lukecampbell can you investigate?

**Comment by lukecampbell** [comment]
The logs have this:

```
Traceback (most recent call last):
  File "/usr/local/bin/sensorml2iso", line 11, in <module>
    load_entry_point('sensorml2iso', 'console_scripts', 'sensorml2iso')()
  File "/srv/app/sensorml2iso/command_line.py", line 98, in main
    obj.run()
  File "/srv/app/sensorml2iso/sensorml2iso.py", line 131, in run
    stations_df = self.get_stations_df(self.service, self.stations)
  File "/srv/app/sensorml2iso/sensorml2iso.py", line 232, in get_stations_df
    sml_recs, sml_errors = sos_collector.metadata_plus_exceptions(output_format=fmt, timeout=200)
  File "/usr/local/lib/python3.5/site-packages/pyoos/collectors/ioos/swe_sos.py", line 62, in metadata_plus_exceptions
    responses[feature] = (SensorML(self.server.describe_sensor(**ds_kwargs)))
  File "/usr/local/lib/python3.5/site-packages/owslib/swe/observation/sos100.py", line 139, in describe_sensor
    response = openURL(base_url, data, method, username=self.username, password=self.password, **url_kwargs).read()
  File "/usr/local/lib/python3.5/site-packages/owslib/util.py", line 183, in openURL
    **rkwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='sdf.ndbc.noaa.gov', port=80): Max retries exceeded with url: /sos/server.php?version=1.0.0&request=DescribeSensor&procedure=urn%3Aioos%3Astation%3Awmo%3A42865&outputFormat=text%2Fxml%3B+subtype%3D%22sensorML%2F1.0.1%2Fprofiles%2Fioos_sos%2F1.0%22&service=SOS (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f5ddf3f1a58>: Failed to establish a new connection: [Errno 113] No route to host',))
```

I restarted the container and CO-OPS and GLOS started harvesting again.

**Comment by lukecampbell** [comment]
I ran it again and it worked. I'm really confused, I haven't made any changes yet, I was still trying to find out what happened and this was the only _error_ in the logs.

**Comment by mwengren** [comment]
Running again now.
