### ISSUE TITLE
IOOS RA portal metadata records don't parse into pycsw

### ISSUE THREAD

**Issue by kwilcox** [ioos/catalog#67]
I think @mwengren created these?

```
ERROR:pycsw.core.admin:Could not parse "/data/dev/pycsw/tests/functionaltests/suites/ioos/data/isos/data.ioos.us/mwengren/ioos/secoora.xml" as an XML record
Traceback (most recent call last):
  File "/data/dev/pycsw/pycsw/core/admin.py", line 347, in load_records
    record = metadata.parse_record(context, exml, repo)
  File "/data/dev/pycsw/pycsw/core/metadata.py", line 119, in parse_record
    return _parse_metadata(context, repos, record)
  File "/data/dev/pycsw/pycsw/core/metadata.py", line 144, in _parse_metadata
    return [_parse_iso(context, repos, exml)]
  File "/data/dev/pycsw/pycsw/core/metadata.py", line 1229, in _parse_iso
    md = MD_Metadata(exml)
  File "/data/conda/miniconda3-py36/envs/pycsw36/lib/python3.6/site-packages/owslib/iso.py", line 146, in __init__
    self.contentinfo.append(MD_FeatureCatalogueDescription(contentinfo))
  File "/data/conda/miniconda3-py36/envs/pycsw36/lib/python3.6/site-packages/owslib/iso.py", line 961, in __init__
    val = i.attrib['uuidref']
  File "src/lxml/lxml.etree.pyx", line 2452, in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:68649)
KeyError: 'uuidref'
```

**Comment by benjwadams** [comment]
@kwilcox, could you elaborate a little more on the issue you're having?
